// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/pb.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/pb.proto

It has these top-level messages:
	Metadata
	BurndownSparseMatrixRow
	BurndownSparseMatrix
	CompressedSparseRowMatrix
	Couples
	TouchedFiles
	DeveloperTouchedFiles
	AnalysisResults
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Metadata struct {
	// this format is versioned
	Version int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// complete command line used to write this message
	Cmdline string `protobuf:"bytes,2,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	// repository's name
	Repository string `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	// timestamp of the first analysed commit
	BeginUnixTime int64 `protobuf:"varint,4,opt,name=begin_unix_time,json=beginUnixTime,proto3" json:"begin_unix_time,omitempty"`
	// timestamp of the last analysed commit
	EndUnixTime int64 `protobuf:"varint,5,opt,name=end_unix_time,json=endUnixTime,proto3" json:"end_unix_time,omitempty"`
	// how many days are in each band [burndown_project, burndown_file, burndown_developer]
	Granularity int32 `protobuf:"varint,6,opt,name=granularity,proto3" json:"granularity,omitempty"`
	// how frequently we measure the state of each band [burndown_project, burndown_file, burndown_developer]
	Sampling int32 `protobuf:"varint,7,opt,name=sampling,proto3" json:"sampling,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{0} }

func (m *Metadata) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Metadata) GetCmdline() string {
	if m != nil {
		return m.Cmdline
	}
	return ""
}

func (m *Metadata) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *Metadata) GetBeginUnixTime() int64 {
	if m != nil {
		return m.BeginUnixTime
	}
	return 0
}

func (m *Metadata) GetEndUnixTime() int64 {
	if m != nil {
		return m.EndUnixTime
	}
	return 0
}

func (m *Metadata) GetGranularity() int32 {
	if m != nil {
		return m.Granularity
	}
	return 0
}

func (m *Metadata) GetSampling() int32 {
	if m != nil {
		return m.Sampling
	}
	return 0
}

type BurndownSparseMatrixRow struct {
	// the first `len(column)` elements are stored,
	// the rest `number_of_columns - len(column)` values are zeros
	Column []uint32 `protobuf:"varint,1,rep,packed,name=column" json:"column,omitempty"`
}

func (m *BurndownSparseMatrixRow) Reset()                    { *m = BurndownSparseMatrixRow{} }
func (m *BurndownSparseMatrixRow) String() string            { return proto.CompactTextString(m) }
func (*BurndownSparseMatrixRow) ProtoMessage()               {}
func (*BurndownSparseMatrixRow) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{1} }

func (m *BurndownSparseMatrixRow) GetColumn() []uint32 {
	if m != nil {
		return m.Column
	}
	return nil
}

type BurndownSparseMatrix struct {
	Name            string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfRows    int32  `protobuf:"varint,2,opt,name=number_of_rows,json=numberOfRows,proto3" json:"number_of_rows,omitempty"`
	NumberOfColumns int32  `protobuf:"varint,3,opt,name=number_of_columns,json=numberOfColumns,proto3" json:"number_of_columns,omitempty"`
	// `len(row)` matches `number_of_rows`
	Row []*BurndownSparseMatrixRow `protobuf:"bytes,4,rep,name=row" json:"row,omitempty"`
}

func (m *BurndownSparseMatrix) Reset()                    { *m = BurndownSparseMatrix{} }
func (m *BurndownSparseMatrix) String() string            { return proto.CompactTextString(m) }
func (*BurndownSparseMatrix) ProtoMessage()               {}
func (*BurndownSparseMatrix) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{2} }

func (m *BurndownSparseMatrix) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BurndownSparseMatrix) GetNumberOfRows() int32 {
	if m != nil {
		return m.NumberOfRows
	}
	return 0
}

func (m *BurndownSparseMatrix) GetNumberOfColumns() int32 {
	if m != nil {
		return m.NumberOfColumns
	}
	return 0
}

func (m *BurndownSparseMatrix) GetRow() []*BurndownSparseMatrixRow {
	if m != nil {
		return m.Row
	}
	return nil
}

type CompressedSparseRowMatrix struct {
	NumberOfRows    int32 `protobuf:"varint,1,opt,name=number_of_rows,json=numberOfRows,proto3" json:"number_of_rows,omitempty"`
	NumberOfColumns int32 `protobuf:"varint,2,opt,name=number_of_columns,json=numberOfColumns,proto3" json:"number_of_columns,omitempty"`
	// https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_.28CSR.2C_CRS_or_Yale_format.29
	Data    []int64 `protobuf:"varint,3,rep,packed,name=data" json:"data,omitempty"`
	Indices []int32 `protobuf:"varint,4,rep,packed,name=indices" json:"indices,omitempty"`
	Indptr  []int64 `protobuf:"varint,5,rep,packed,name=indptr" json:"indptr,omitempty"`
}

func (m *CompressedSparseRowMatrix) Reset()                    { *m = CompressedSparseRowMatrix{} }
func (m *CompressedSparseRowMatrix) String() string            { return proto.CompactTextString(m) }
func (*CompressedSparseRowMatrix) ProtoMessage()               {}
func (*CompressedSparseRowMatrix) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{3} }

func (m *CompressedSparseRowMatrix) GetNumberOfRows() int32 {
	if m != nil {
		return m.NumberOfRows
	}
	return 0
}

func (m *CompressedSparseRowMatrix) GetNumberOfColumns() int32 {
	if m != nil {
		return m.NumberOfColumns
	}
	return 0
}

func (m *CompressedSparseRowMatrix) GetData() []int64 {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CompressedSparseRowMatrix) GetIndices() []int32 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *CompressedSparseRowMatrix) GetIndptr() []int64 {
	if m != nil {
		return m.Indptr
	}
	return nil
}

type Couples struct {
	// name of each `matrix`'s row and column
	Index []string `protobuf:"bytes,1,rep,name=index" json:"index,omitempty"`
	// is always square
	Matrix *CompressedSparseRowMatrix `protobuf:"bytes,2,opt,name=matrix" json:"matrix,omitempty"`
}

func (m *Couples) Reset()                    { *m = Couples{} }
func (m *Couples) String() string            { return proto.CompactTextString(m) }
func (*Couples) ProtoMessage()               {}
func (*Couples) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{4} }

func (m *Couples) GetIndex() []string {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *Couples) GetMatrix() *CompressedSparseRowMatrix {
	if m != nil {
		return m.Matrix
	}
	return nil
}

type TouchedFiles struct {
	File []int32 `protobuf:"varint,1,rep,packed,name=file" json:"file,omitempty"`
}

func (m *TouchedFiles) Reset()                    { *m = TouchedFiles{} }
func (m *TouchedFiles) String() string            { return proto.CompactTextString(m) }
func (*TouchedFiles) ProtoMessage()               {}
func (*TouchedFiles) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{5} }

func (m *TouchedFiles) GetFile() []int32 {
	if m != nil {
		return m.File
	}
	return nil
}

type DeveloperTouchedFiles struct {
	// order corresponds to `developer_couples::index`
	Developer []*TouchedFiles `protobuf:"bytes,1,rep,name=developer" json:"developer,omitempty"`
}

func (m *DeveloperTouchedFiles) Reset()                    { *m = DeveloperTouchedFiles{} }
func (m *DeveloperTouchedFiles) String() string            { return proto.CompactTextString(m) }
func (*DeveloperTouchedFiles) ProtoMessage()               {}
func (*DeveloperTouchedFiles) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{6} }

func (m *DeveloperTouchedFiles) GetDeveloper() []*TouchedFiles {
	if m != nil {
		return m.Developer
	}
	return nil
}

type AnalysisResults struct {
	// these two are always included
	Header          *Metadata             `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	BurndownProject *BurndownSparseMatrix `protobuf:"bytes,2,opt,name=burndown_project,json=burndownProject" json:"burndown_project,omitempty"`
	// this is included if `-files` was specified
	BurndownFile []*BurndownSparseMatrix `protobuf:"bytes,3,rep,name=burndown_file,json=burndownFile" json:"burndown_file,omitempty"`
	// these two are included if `-people` was specified
	BurndownDeveloper []*BurndownSparseMatrix `protobuf:"bytes,4,rep,name=burndown_developer,json=burndownDeveloper" json:"burndown_developer,omitempty"`
	// rows and cols order correspond to `burndown_developer`
	DevelopersInteraction *CompressedSparseRowMatrix `protobuf:"bytes,5,opt,name=developers_interaction,json=developersInteraction" json:"developers_interaction,omitempty"`
	// these three are included if `-couples` was specified
	FileCouples      *Couples               `protobuf:"bytes,6,opt,name=file_couples,json=fileCouples" json:"file_couples,omitempty"`
	DeveloperCouples *Couples               `protobuf:"bytes,7,opt,name=developer_couples,json=developerCouples" json:"developer_couples,omitempty"`
	TouchedFiles     *DeveloperTouchedFiles `protobuf:"bytes,8,opt,name=touched_files,json=touchedFiles" json:"touched_files,omitempty"`
}

func (m *AnalysisResults) Reset()                    { *m = AnalysisResults{} }
func (m *AnalysisResults) String() string            { return proto.CompactTextString(m) }
func (*AnalysisResults) ProtoMessage()               {}
func (*AnalysisResults) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{7} }

func (m *AnalysisResults) GetHeader() *Metadata {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AnalysisResults) GetBurndownProject() *BurndownSparseMatrix {
	if m != nil {
		return m.BurndownProject
	}
	return nil
}

func (m *AnalysisResults) GetBurndownFile() []*BurndownSparseMatrix {
	if m != nil {
		return m.BurndownFile
	}
	return nil
}

func (m *AnalysisResults) GetBurndownDeveloper() []*BurndownSparseMatrix {
	if m != nil {
		return m.BurndownDeveloper
	}
	return nil
}

func (m *AnalysisResults) GetDevelopersInteraction() *CompressedSparseRowMatrix {
	if m != nil {
		return m.DevelopersInteraction
	}
	return nil
}

func (m *AnalysisResults) GetFileCouples() *Couples {
	if m != nil {
		return m.FileCouples
	}
	return nil
}

func (m *AnalysisResults) GetDeveloperCouples() *Couples {
	if m != nil {
		return m.DeveloperCouples
	}
	return nil
}

func (m *AnalysisResults) GetTouchedFiles() *DeveloperTouchedFiles {
	if m != nil {
		return m.TouchedFiles
	}
	return nil
}

func init() {
	proto.RegisterType((*Metadata)(nil), "Metadata")
	proto.RegisterType((*BurndownSparseMatrixRow)(nil), "BurndownSparseMatrixRow")
	proto.RegisterType((*BurndownSparseMatrix)(nil), "BurndownSparseMatrix")
	proto.RegisterType((*CompressedSparseRowMatrix)(nil), "CompressedSparseRowMatrix")
	proto.RegisterType((*Couples)(nil), "Couples")
	proto.RegisterType((*TouchedFiles)(nil), "TouchedFiles")
	proto.RegisterType((*DeveloperTouchedFiles)(nil), "DeveloperTouchedFiles")
	proto.RegisterType((*AnalysisResults)(nil), "AnalysisResults")
}

func init() { proto.RegisterFile("pb/pb.proto", fileDescriptorPb) }

var fileDescriptorPb = []byte{
	// 639 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x96, 0x6b, 0x3b, 0x1f, 0xe3, 0xe4, 0x4d, 0xbb, 0x6a, 0xfb, 0xfa, 0xed, 0xe1, 0x55, 0xb0,
	0x10, 0x8a, 0x5a, 0xc9, 0x88, 0x20, 0x2e, 0x70, 0x01, 0x5a, 0x21, 0x71, 0xa8, 0x80, 0x6d, 0x39,
	0x5b, 0x8e, 0x3d, 0x6d, 0x17, 0xd9, 0xbb, 0xd6, 0xee, 0xba, 0x49, 0xff, 0x11, 0x77, 0xfe, 0x14,
	0x07, 0x7e, 0x04, 0xf2, 0xfa, 0x23, 0x01, 0x52, 0xe0, 0xe6, 0x99, 0x79, 0x9e, 0xf1, 0xf3, 0xcc,
	0x8c, 0x0d, 0x5e, 0xb1, 0x78, 0x5c, 0x2c, 0xc2, 0x42, 0x0a, 0x2d, 0x82, 0xaf, 0x16, 0x0c, 0xce,
	0x51, 0xc7, 0x69, 0xac, 0x63, 0xe2, 0x43, 0xff, 0x16, 0xa5, 0x62, 0x82, 0xfb, 0xd6, 0xd4, 0x9a,
	0xb9, 0xb4, 0x0d, 0xab, 0x4a, 0x92, 0xa7, 0x19, 0xe3, 0xe8, 0xef, 0x4c, 0xad, 0xd9, 0x90, 0xb6,
	0x21, 0xf9, 0x1f, 0x40, 0x62, 0x21, 0x14, 0xd3, 0x42, 0xde, 0xf9, 0xb6, 0x29, 0x6e, 0x64, 0xc8,
	0x23, 0x98, 0x2c, 0xf0, 0x9a, 0xf1, 0xa8, 0xe4, 0x6c, 0x15, 0x69, 0x96, 0xa3, 0xef, 0x4c, 0xad,
	0x99, 0x4d, 0xc7, 0x26, 0xfd, 0x91, 0xb3, 0xd5, 0x25, 0xcb, 0x91, 0x04, 0x30, 0x46, 0x9e, 0x6e,
	0xa0, 0x5c, 0x83, 0xf2, 0x90, 0xa7, 0x1d, 0x66, 0x0a, 0xde, 0xb5, 0x8c, 0x79, 0x99, 0xc5, 0x92,
	0xe9, 0x3b, 0xbf, 0x67, 0x34, 0x6e, 0xa6, 0xc8, 0x11, 0x0c, 0x54, 0x9c, 0x17, 0x19, 0xe3, 0xd7,
	0x7e, 0xdf, 0x94, 0xbb, 0x38, 0x78, 0x02, 0xff, 0xbe, 0x2e, 0x25, 0x4f, 0xc5, 0x92, 0x5f, 0x14,
	0xb1, 0x54, 0x78, 0x1e, 0x6b, 0xc9, 0x56, 0x54, 0x2c, 0xc9, 0x21, 0xf4, 0x12, 0x91, 0x95, 0x79,
	0xe5, 0xdb, 0x9e, 0x8d, 0x69, 0x13, 0x05, 0x9f, 0x2d, 0xd8, 0xdf, 0xc6, 0x21, 0x04, 0x1c, 0x1e,
	0xe7, 0x68, 0xc6, 0x34, 0xa4, 0xe6, 0x99, 0x3c, 0x84, 0x7f, 0x78, 0x99, 0x2f, 0x50, 0x46, 0xe2,
	0x2a, 0x92, 0x62, 0xa9, 0xcc, 0xa8, 0x5c, 0x3a, 0xaa, 0xb3, 0xef, 0xae, 0xa8, 0x58, 0x2a, 0x72,
	0x0c, 0x7b, 0x6b, 0x54, 0xfd, 0x1a, 0x65, 0xc6, 0xe6, 0xd2, 0x49, 0x0b, 0x3c, 0xad, 0xd3, 0xe4,
	0x18, 0x6c, 0x29, 0x96, 0xbe, 0x33, 0xb5, 0x67, 0xde, 0xdc, 0x0f, 0xef, 0x51, 0x4f, 0x2b, 0x50,
	0xf0, 0xc5, 0x82, 0xff, 0x4e, 0x45, 0x5e, 0x48, 0x54, 0x0a, 0xd3, 0x1a, 0x42, 0xc5, 0xb2, 0xd1,
	0xfb, 0xab, 0x36, 0xeb, 0x6f, 0xb5, 0xed, 0x6c, 0xd7, 0x46, 0xc0, 0xa9, 0x6e, 0xc6, 0xb7, 0xa7,
	0xf6, 0xcc, 0xa6, 0x4e, 0x7b, 0x3f, 0x8c, 0xa7, 0x2c, 0x41, 0x65, 0x34, 0xbb, 0xb4, 0x0d, 0xab,
	0x01, 0x33, 0x9e, 0x16, 0x5a, 0xfa, 0xae, 0xc1, 0x37, 0x51, 0x70, 0x01, 0xfd, 0x53, 0x51, 0x16,
	0x19, 0x2a, 0xb2, 0x0f, 0x2e, 0xe3, 0x29, 0xae, 0xcc, 0x0a, 0x86, 0xb4, 0x0e, 0xc8, 0x1c, 0x7a,
	0xb9, 0xb1, 0x60, 0x74, 0x78, 0xf3, 0xa3, 0xf0, 0x5e, 0x93, 0xb4, 0x41, 0x06, 0x01, 0x8c, 0x2e,
	0x45, 0x99, 0xdc, 0x60, 0xfa, 0x86, 0x55, 0x9d, 0x09, 0x38, 0x57, 0x2c, 0x43, 0xd3, 0xd8, 0xa5,
	0xe6, 0x39, 0x38, 0x83, 0x83, 0x33, 0xbc, 0xc5, 0x4c, 0x14, 0x28, 0x7f, 0x00, 0x9f, 0xc0, 0x30,
	0x6d, 0x0b, 0x86, 0xe1, 0xcd, 0xc7, 0xe1, 0x26, 0x82, 0xae, 0xeb, 0xc1, 0x37, 0x1b, 0x26, 0xaf,
	0x78, 0x9c, 0xdd, 0x29, 0xa6, 0x28, 0xaa, 0x32, 0xd3, 0x8a, 0x3c, 0x80, 0xde, 0x0d, 0xc6, 0xa9,
	0x61, 0x57, 0x8a, 0x87, 0x61, 0xfb, 0x7d, 0xd1, 0xa6, 0x40, 0x5e, 0xc2, 0xee, 0xa2, 0xd9, 0x65,
	0x54, 0x48, 0xf1, 0x09, 0x13, 0xdd, 0xd8, 0x3b, 0xd8, 0xbe, 0xe4, 0x49, 0x0b, 0x7f, 0x5f, 0xa3,
	0xc9, 0x73, 0x18, 0x77, 0x1d, 0x8c, 0x37, 0xdb, 0x28, 0xbd, 0x87, 0x3e, 0x6a, 0xb1, 0x95, 0x01,
	0x72, 0x06, 0xa4, 0xe3, 0xae, 0xad, 0x3a, 0xbf, 0x6b, 0xb0, 0xd7, 0x12, 0xba, 0x99, 0x91, 0x0f,
	0x70, 0xd8, 0x91, 0x55, 0xc4, 0xb8, 0x46, 0x19, 0x27, 0xba, 0xfa, 0x75, 0xb8, 0x7f, 0x5c, 0xd4,
	0xc1, 0x9a, 0xf9, 0x76, 0x4d, 0x24, 0x27, 0x30, 0xaa, 0xbc, 0x44, 0x49, 0x7d, 0x11, 0xe6, 0xfb,
	0xf6, 0xe6, 0x83, 0xb0, 0xb9, 0x10, 0xea, 0x55, 0xd5, 0xf6, 0x5c, 0x9e, 0xc1, 0x5e, 0xd7, 0xa5,
	0x63, 0xf4, 0x7f, 0x62, 0xec, 0x76, 0x90, 0x96, 0xf6, 0x02, 0xc6, 0xba, 0x5e, 0xa6, 0x99, 0x9b,
	0xf2, 0x07, 0x86, 0x72, 0x18, 0x6e, 0xbd, 0x06, 0x3a, 0xd2, 0x1b, 0xd1, 0xa2, 0x67, 0xfe, 0x99,
	0x4f, 0xbf, 0x07, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xad, 0x60, 0xf9, 0x42, 0x05, 0x00, 0x00,
}
