# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/pb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/pb.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bpb/pb.proto\"\x97\x01\n\x08Metadata\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0f\n\x07\x63mdline\x18\x02 \x01(\t\x12\x12\n\nrepository\x18\x03 \x01(\t\x12\x17\n\x0f\x62\x65gin_unix_time\x18\x04 \x01(\x03\x12\x15\n\rend_unix_time\x18\x05 \x01(\x03\x12\x13\n\x0bgranularity\x18\x06 \x01(\x05\x12\x10\n\x08sampling\x18\x07 \x01(\x05\"*\n\x17\x42urndownSparseMatrixRow\x12\x0f\n\x07\x63olumns\x18\x01 \x03(\r\"\x7f\n\x14\x42urndownSparseMatrix\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0enumber_of_rows\x18\x02 \x01(\x05\x12\x19\n\x11number_of_columns\x18\x03 \x01(\x05\x12&\n\x04rows\x18\x04 \x03(\x0b\x32\x18.BurndownSparseMatrixRow\"}\n\x19\x43ompressedSparseRowMatrix\x12\x16\n\x0enumber_of_rows\x18\x01 \x01(\x05\x12\x19\n\x11number_of_columns\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x03\x12\x0f\n\x07indices\x18\x04 \x03(\x05\x12\x0e\n\x06indptr\x18\x05 \x03(\x03\"D\n\x07\x43ouples\x12\r\n\x05index\x18\x01 \x03(\t\x12*\n\x06matrix\x18\x02 \x01(\x0b\x32\x1a.CompressedSparseRowMatrix\"\x1d\n\x0cTouchedFiles\x12\r\n\x05\x66iles\x18\x01 \x03(\x05\":\n\x15\x44\x65veloperTouchedFiles\x12!\n\ndevelopers\x18\x01 \x03(\x0b\x32\r.TouchedFiles\"\xf0\x02\n\x0f\x41nalysisResults\x12\x19\n\x06header\x18\x01 \x01(\x0b\x32\t.Metadata\x12/\n\x10\x62urndown_project\x18\x02 \x01(\x0b\x32\x15.BurndownSparseMatrix\x12-\n\x0e\x62urndown_files\x18\x03 \x03(\x0b\x32\x15.BurndownSparseMatrix\x12\x32\n\x13\x62urndown_developers\x18\x04 \x03(\x0b\x32\x15.BurndownSparseMatrix\x12:\n\x16\x64\x65velopers_interaction\x18\x05 \x01(\x0b\x32\x1a.CompressedSparseRowMatrix\x12\x1e\n\x0c\x66ile_couples\x18\x06 \x01(\x0b\x32\x08.Couples\x12#\n\x11\x64\x65veloper_couples\x18\x07 \x01(\x0b\x32\x08.Couples\x12-\n\rtouched_files\x18\x08 \x01(\x0b\x32\x16.DeveloperTouchedFilesb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Metadata.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmdline', full_name='Metadata.cmdline', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repository', full_name='Metadata.repository', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='begin_unix_time', full_name='Metadata.begin_unix_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_unix_time', full_name='Metadata.end_unix_time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='granularity', full_name='Metadata.granularity', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sampling', full_name='Metadata.sampling', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=167,
)


_BURNDOWNSPARSEMATRIXROW = _descriptor.Descriptor(
  name='BurndownSparseMatrixRow',
  full_name='BurndownSparseMatrixRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columns', full_name='BurndownSparseMatrixRow.columns', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=211,
)


_BURNDOWNSPARSEMATRIX = _descriptor.Descriptor(
  name='BurndownSparseMatrix',
  full_name='BurndownSparseMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BurndownSparseMatrix.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_rows', full_name='BurndownSparseMatrix.number_of_rows', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_columns', full_name='BurndownSparseMatrix.number_of_columns', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='BurndownSparseMatrix.rows', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=340,
)


_COMPRESSEDSPARSEROWMATRIX = _descriptor.Descriptor(
  name='CompressedSparseRowMatrix',
  full_name='CompressedSparseRowMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_rows', full_name='CompressedSparseRowMatrix.number_of_rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_columns', full_name='CompressedSparseRowMatrix.number_of_columns', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='CompressedSparseRowMatrix.data', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='indices', full_name='CompressedSparseRowMatrix.indices', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='indptr', full_name='CompressedSparseRowMatrix.indptr', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=467,
)


_COUPLES = _descriptor.Descriptor(
  name='Couples',
  full_name='Couples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Couples.index', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matrix', full_name='Couples.matrix', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=537,
)


_TOUCHEDFILES = _descriptor.Descriptor(
  name='TouchedFiles',
  full_name='TouchedFiles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='files', full_name='TouchedFiles.files', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=568,
)


_DEVELOPERTOUCHEDFILES = _descriptor.Descriptor(
  name='DeveloperTouchedFiles',
  full_name='DeveloperTouchedFiles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='developers', full_name='DeveloperTouchedFiles.developers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=628,
)


_ANALYSISRESULTS = _descriptor.Descriptor(
  name='AnalysisResults',
  full_name='AnalysisResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='AnalysisResults.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='burndown_project', full_name='AnalysisResults.burndown_project', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='burndown_files', full_name='AnalysisResults.burndown_files', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='burndown_developers', full_name='AnalysisResults.burndown_developers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='developers_interaction', full_name='AnalysisResults.developers_interaction', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_couples', full_name='AnalysisResults.file_couples', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='developer_couples', full_name='AnalysisResults.developer_couples', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='touched_files', full_name='AnalysisResults.touched_files', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=631,
  serialized_end=999,
)

_BURNDOWNSPARSEMATRIX.fields_by_name['rows'].message_type = _BURNDOWNSPARSEMATRIXROW
_COUPLES.fields_by_name['matrix'].message_type = _COMPRESSEDSPARSEROWMATRIX
_DEVELOPERTOUCHEDFILES.fields_by_name['developers'].message_type = _TOUCHEDFILES
_ANALYSISRESULTS.fields_by_name['header'].message_type = _METADATA
_ANALYSISRESULTS.fields_by_name['burndown_project'].message_type = _BURNDOWNSPARSEMATRIX
_ANALYSISRESULTS.fields_by_name['burndown_files'].message_type = _BURNDOWNSPARSEMATRIX
_ANALYSISRESULTS.fields_by_name['burndown_developers'].message_type = _BURNDOWNSPARSEMATRIX
_ANALYSISRESULTS.fields_by_name['developers_interaction'].message_type = _COMPRESSEDSPARSEROWMATRIX
_ANALYSISRESULTS.fields_by_name['file_couples'].message_type = _COUPLES
_ANALYSISRESULTS.fields_by_name['developer_couples'].message_type = _COUPLES
_ANALYSISRESULTS.fields_by_name['touched_files'].message_type = _DEVELOPERTOUCHEDFILES
DESCRIPTOR.message_types_by_name['Metadata'] = _METADATA
DESCRIPTOR.message_types_by_name['BurndownSparseMatrixRow'] = _BURNDOWNSPARSEMATRIXROW
DESCRIPTOR.message_types_by_name['BurndownSparseMatrix'] = _BURNDOWNSPARSEMATRIX
DESCRIPTOR.message_types_by_name['CompressedSparseRowMatrix'] = _COMPRESSEDSPARSEROWMATRIX
DESCRIPTOR.message_types_by_name['Couples'] = _COUPLES
DESCRIPTOR.message_types_by_name['TouchedFiles'] = _TOUCHEDFILES
DESCRIPTOR.message_types_by_name['DeveloperTouchedFiles'] = _DEVELOPERTOUCHEDFILES
DESCRIPTOR.message_types_by_name['AnalysisResults'] = _ANALYSISRESULTS

Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), dict(
  DESCRIPTOR = _METADATA,
  __module__ = 'pb.pb_pb2'
  # @@protoc_insertion_point(class_scope:Metadata)
  ))
_sym_db.RegisterMessage(Metadata)

BurndownSparseMatrixRow = _reflection.GeneratedProtocolMessageType('BurndownSparseMatrixRow', (_message.Message,), dict(
  DESCRIPTOR = _BURNDOWNSPARSEMATRIXROW,
  __module__ = 'pb.pb_pb2'
  # @@protoc_insertion_point(class_scope:BurndownSparseMatrixRow)
  ))
_sym_db.RegisterMessage(BurndownSparseMatrixRow)

BurndownSparseMatrix = _reflection.GeneratedProtocolMessageType('BurndownSparseMatrix', (_message.Message,), dict(
  DESCRIPTOR = _BURNDOWNSPARSEMATRIX,
  __module__ = 'pb.pb_pb2'
  # @@protoc_insertion_point(class_scope:BurndownSparseMatrix)
  ))
_sym_db.RegisterMessage(BurndownSparseMatrix)

CompressedSparseRowMatrix = _reflection.GeneratedProtocolMessageType('CompressedSparseRowMatrix', (_message.Message,), dict(
  DESCRIPTOR = _COMPRESSEDSPARSEROWMATRIX,
  __module__ = 'pb.pb_pb2'
  # @@protoc_insertion_point(class_scope:CompressedSparseRowMatrix)
  ))
_sym_db.RegisterMessage(CompressedSparseRowMatrix)

Couples = _reflection.GeneratedProtocolMessageType('Couples', (_message.Message,), dict(
  DESCRIPTOR = _COUPLES,
  __module__ = 'pb.pb_pb2'
  # @@protoc_insertion_point(class_scope:Couples)
  ))
_sym_db.RegisterMessage(Couples)

TouchedFiles = _reflection.GeneratedProtocolMessageType('TouchedFiles', (_message.Message,), dict(
  DESCRIPTOR = _TOUCHEDFILES,
  __module__ = 'pb.pb_pb2'
  # @@protoc_insertion_point(class_scope:TouchedFiles)
  ))
_sym_db.RegisterMessage(TouchedFiles)

DeveloperTouchedFiles = _reflection.GeneratedProtocolMessageType('DeveloperTouchedFiles', (_message.Message,), dict(
  DESCRIPTOR = _DEVELOPERTOUCHEDFILES,
  __module__ = 'pb.pb_pb2'
  # @@protoc_insertion_point(class_scope:DeveloperTouchedFiles)
  ))
_sym_db.RegisterMessage(DeveloperTouchedFiles)

AnalysisResults = _reflection.GeneratedProtocolMessageType('AnalysisResults', (_message.Message,), dict(
  DESCRIPTOR = _ANALYSISRESULTS,
  __module__ = 'pb.pb_pb2'
  # @@protoc_insertion_point(class_scope:AnalysisResults)
  ))
_sym_db.RegisterMessage(AnalysisResults)


# @@protoc_insertion_point(module_scope)
